### ISSUE TITLE
Crash on DragGestureDetectorKt

### ISSUE THREAD

**Issue by riggaroo** [godaddy/compose-color-picker#11]
Mostly seems to be happening to Android 11 and Android 9 samsung devices.

```
Fatal Exception: java.lang.NullPointerException
       at androidx.compose.foundation.gestures.DragGestureDetectorKt.awaitDragOrCancellation-rnUCldI(DragGestureDetectorKt.java:844)
       at androidx.compose.foundation.gestures.DragGestureDetectorKt$awaitDragOrCancellation$1.invokeSuspend(DragGestureDetectorKt.java:12)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTaskKt.java:178)
       at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTaskKt.java:166)
       at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.java:397)
       at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.java:431)
       at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.java:420)
       at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.java:328)
       at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.java:511)
       at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.dispatchPointerEvent(SuspendingPointerInputFilter.java:407)
       at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.java:420)
       at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(Node.java:284)
       at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(NodeParent.java:151)
       at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.java:88)
       at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.java:80)
       at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(AndroidComposeView.java:961)
       at androidx.compose.ui.platform.AndroidComposeView.dispatchHoverEvent(AndroidComposeView.java:1123)
       at android.view.View.dispatchGenericMotionEvent(View.java:15309)
       at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2640)
       at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:2222)
       at android.view.View.dispatchGenericMotionEvent(View.java:15309)
       at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2640)
       at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:2222)
       at android.view.View.dispatchGenericMotionEvent(View.java:15309)
       at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2640)
       at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:2222)
       at android.view.View.dispatchGenericMotionEvent(View.java:15309)
       at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2640)
       at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:2222)
       at android.view.View.dispatchGenericMotionEvent(View.java:15309)
       at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2640)
       at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:2222)
       at android.view.View.dispatchGenericMotionEvent(View.java:15309)
       at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2640)
       at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:2222)
       at android.view.View.dispatchGenericMotionEvent(View.java:15309)
       at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2640)
       at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:2222)
       at android.view.View.dispatchGenericMotionEvent(View.java:15309)
       at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2640)
       at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:2222)
       at android.view.View.dispatchGenericMotionEvent(View.java:15309)
       at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2640)
       at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:2222)
       at android.view.View.dispatchGenericMotionEvent(View.java:15309)
       at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2640)
       at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:2222)
       at com.android.internal.policy.DecorView.dispatchHoverEvent(DecorView.java:4195)
       at android.view.View.dispatchGenericMotionEvent(View.java:15309)
       at com.android.internal.policy.DecorView.superDispatchGenericMotionEvent(DecorView.java:921)
       at com.android.internal.policy.PhoneWindow.superDispatchGenericMotionEvent(PhoneWindow.java:1967)
       at android.app.Activity.dispatchGenericMotionEvent(Activity.java:4218)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchGenericMotionEvent(WindowCallbackWrapper.java:79)
       at com.android.internal.policy.DecorView.dispatchGenericMotionEvent(DecorView.java:885)
       at android.view.View.dispatchPointerEvent(View.java:15460)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7457)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7233)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6595)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6786)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6843)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9880)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9718)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9671)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10014)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loop(Looper.java:206)
       at android.app.ActivityThread.main(ActivityThread.java:8595)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by riggaroo** [comment]
Seems similar to this issue mentioned here: https://github.com/JetBrains/compose-jb/issues/1426

**Comment by riggaroo** [comment]
https://issuetracker.google.com/issues/202410799
